### ISSUE TITLE
I got a problem when I try to python waf configure --ns3-path=~/ns-3-dev

### ISSUE THREAD

**Issue by tianxingyang** [steinwurf/kodo-ns3-examples#36]
ytx@ubuntu:~/kodo-ns3-examples$ python waf configure --ns3-path=~/ns-3-dev
Setting top to                           : /home/ytx/kodo-ns3-examples 
Setting out to                           : /home/ytx/kodo-ns3-examples/build/linux 
Checking for program 'git'               : ['/usr/bin/git'] 
Resolve dependency sak                   : /home/ytx/kodo-ns3-examples/bundle_dependencies/sak-2baed8/12.1.0 
Resolve dependency kodo                  : Command ['/usr/bin/git', 'clone', 'git@github.com:steinwurf/kodo.git', '/home/ytx/kodo-ns3-examples/bundle_dependencies/kodo-f3a9b9/master'] returned 128
What's wrong with it? I cannot figure it out.

**Comment by nestorjhernandezm** [comment]
Hi,

By the information that you are providing us here, there is a problem when
waf tries to clone kodo which of course is a dependency for the project.
Reading a bit about in the web, the command "git clone" returns 128 when it
detects a misconfigurations with the ssh keys (and you are identifying
yourself with ssh for the cloning here). However, other errors might be
giving the 128 signal error because you were able to clone sak.

You can verify if this is the problem by trying to run yourself:
/usr/bin/git clone git@github.com:steinwurf/kodo.git
/home/ytx/kodo-ns3-examples/bundle_dependencies/kodo-f3a9b9/master

...and see the output of the git command to help us to verify the problem.
If (for some reason) the ssh keys are the problem, you may not be able to
clone other repositories as well.

Please let me know how it goes.

Best,

2015-06-11 4:56 GMT+02:00 杨天幸 <notifications@github.com>:

> ytx@ubuntu:~/kodo-ns3-examples$ python waf configure --ns3-path=~/ns-3-dev
> Setting top to : /home/ytx/kodo-ns3-examples
> Setting out to : /home/ytx/kodo-ns3-examples/build/linux
> Checking for program 'git' : ['/usr/bin/git']
> Resolve dependency sak :
> /home/ytx/kodo-ns3-examples/bundle_dependencies/sak-2baed8/12.1.0
> Resolve dependency kodo : Command ['/usr/bin/git', 'clone', '
> git@github.com:steinwurf/kodo.git',
> '/home/ytx/kodo-ns3-examples/bundle_dependencies/kodo-f3a9b9/master']
> returned 128
> What's wrong with it? I cannot figure it out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steinwurf/kodo-ns3-examples/issues/36>.
>



-- 
Néstor Hernández
Mobile: +4551200349

**Comment by mortenvp** [comment]
Did you sign-up for the Kodo research license? Otherwise you don't have access to that repository - which may be why you get an error.

**Comment by nestorjhernandezm** [comment]
Actually what Morten points out is more relevant in the first place.

There has been some policy changes in the distribution of Kodo, so you need
to apply for a license in case you don't have it now.

Best,


2015-06-11 21:47 GMT+02:00 Morten V. Pedersen <notifications@github.com>:

> Did you sign-up for the Kodo research license? Otherwise you don't have
> access to that repository - which may be why you get an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steinwurf/kodo-ns3-examples/issues/36#issuecomment-111257153>
> .
>



-- 
Néstor Hernández
Mobile: +4551200349

**Comment by tianxingyang** [comment]
When I trying to run the first one, it returns Repository not found. Here is the output.
ytx@ubuntu:~$ /usr/bin/git clone git@github.com:steinwurf/kodo.git
Cloning into 'kodo'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

As for the second one, there is no file named master in my /home/ytx/kodo-ns3-examples/bundle_dependencies/kodo-f3a9b9/
@nestorjhernandezm

**Comment by nestorjhernandezm** [comment]
Hi Tian,

Morten also pointed out something important last time. Did you submit a license request form and had granted access to the repository?

E.g. Did you fill the form here: http://steinwurf.com/license/ ?

If you don't have access, that is more likely why you are not able to clone the kodo repository. Let's make sure that you have everything what you need on your side.

**Comment by mortenvp** [comment]
@tianxingyang I just checked and you do not have access to the Kodo repository - you need to sign-up for a research license first.

**Comment by mortenvp** [comment]
I'm closing this issue - if you still have problems after obtaining a research license (from http://steinwurf.com/license) - feel free to reopen the issue.
